### ISSUE TITLE
How use Autoprefixer with SCSS file?

### ISSUE THREAD

**Issue by mrpierrot** [brunch/postcss-brunch#41]
Hi,

I want to prefix scss file with autoprefixer. But, it's not working. 
I find this https://github.com/postcss/postcss-scss who necessary for prefixing scss file, but I don't know who use it in brunch config. 

Could you help me, please?

Thanks

**Comment by denysdovhan** [comment]
Hi, @mrpierrot! Thanks for your question.

You can't do that at the moment, because plugin's options aren't being passed to the PostCSS directly. My PR #42 introduce that feature.

@shvaikalesh, please check. I'm not sure about implementation. I know you've planed to rewrite this plugin, so probably this PR isn't needed.

**Comment by mrpierrot** [comment]
Hi @denysdovhan !
Thank you for your response. :-)
I'd watch that!

**Comment by iamvdo** [comment]
@mrpierrot: You could also test https://github.com/iamvdo/pleeease-brunch package, which is a ready-to-go plugin. Maybe a bit old, but it used to work.

**Comment by mrpierrot** [comment]
@iamvdo Thank you, I will test this!

**Comment by jfilter** [comment]
Yes, it works with https://github.com/iamvdo/pleeease-brunch.
